### ISSUE TITLE
Unitwise::Unit.new("atm") fails

### ISSUE THREAD

**Issue by turboladen** [joshwlewis/unitwise#57]
Looks like it should be supported; it's in the YAML file [here](https://github.com/joshwlewis/unitwise/blob/f786d2e660721a0238949e7abce20852879de8ef/data/derived_unit.yaml#L772).

Here's what I'm getting:

```
198:0> Unitwise::Unit.new("atm")
Traceback (most recent call last):
       13: from /Users/sloveless/.rubies/ruby-2.5.1/bin/irb:11:in `<main>'
       12: from /Users/sloveless/.gem/ruby/2.5.1/gems/liner-0.2.4/lib/liner/inspectable.rb:7:in `inspect'
       11: from /Users/sloveless/.gem/ruby/2.5.1/gems/liner-0.2.4/lib/liner/inspectable.rb:15:in `attribute_string'
       10: from /Users/sloveless/.gem/ruby/2.5.1/gems/liner-0.2.4/lib/liner/hashable.rb:29:in `liner'
        9: from /Users/sloveless/.gem/ruby/2.5.1/gems/liner-0.2.4/lib/liner/hashable.rb:29:in `inject'
        8: from /Users/sloveless/.gem/ruby/2.5.1/gems/liner-0.2.4/lib/liner/hashable.rb:29:in `each'
        7: from /Users/sloveless/.gem/ruby/2.5.1/gems/liner-0.2.4/lib/liner/hashable.rb:29:in `block in liner'
        6: from /Users/sloveless/.gem/ruby/2.5.1/gems/liner-0.2.4/lib/liner/hashable.rb:9:in `[]'
        5: from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/unit.rb:30:in `terms'
        4: from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/expression.rb:30:in `decompose'
        3: from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/expression/decomposer.rb:17:in `parse'
        2: from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/expression/decomposer.rb:17:in `new'
        1: from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/expression/decomposer.rb:54:in `initialize'
Unitwise::ExpressionError (Could not evaluate 'atm'.)
199:0> Unitwise::VERSION
➥ "2.2.0"
200:0> RUBY_VERSION
➥ "2.5.1"
```

**Comment by stevegeek** [comment]
Ok thanks for the extra detail! Will try get to the bottom of it

**Comment by stevegeek** [comment]
Yeah I need to look more as the UCUM spec. It says near the top:

```
ISO 2955 and ANSI X3.50 contain numerous name conflicts, both direct conflicts (e.g., “a” being used for both “year” and “are”) and conflicts that are generated through combination of unit symbols with prefixes (e.g., “cd” means candela and centi-day and “PEV” means peta-volt and pico-electronvolt.)
```

But even UCUM has some conflicts in the end

```
Summary of Conflicts

The Unified Code for Units of Measure is designed and maintained so that severe name conflicts do not occur. However, avoiding all conflicts is possible only at the cost of defining very unusual symbols for those units. As the [Table 25](https://ucum.org/ucum#conflicts) shows, all current conflicts are of type IVa between metric and nonmetric units. This means that there is only a conflict if the metric predicate is violated so that non-metric units are used with a prefix. [Schadow G, McDonald CJ et al: Units of Measure in Clinical Information Systems. JAMIA 6(2); Mar/Apr 1999. p. 151-162.]

Table 25: Summary of name conflicts
Gb	G-b	Type IVa (metric-nonmetric)
Pa	P-a	Type IVa (metric-nonmetric)
ph	p-h	Type IVa (metric-nonmetric)
cd	c-d	Type IVa (metric-nonmetric)
CD	C-D	Type IVa (metric-nonmetric)
```

**Comment by stevegeek** [comment]
I think a strict UCUM parser (which then requires use of UCUM codes eg `[ft_i]`) should be an available parser, while another parser would let one also use the more "natural" symbol set (that unitwise supports eg `ft` for foot) and it would favour base units over prefixed ones. It should probably also have configurable behaviour on conflicts and be able to generate warnings when conflicts do occur. Then the user can decide what they need (eg for my project using unitwise I use UCUM codes anyway)
