### ISSUE TITLE
NoMethodError: undefined method `from_100tan' for Unitwise::Functional:Class

### ISSUE THREAD

**Issue by turboladen** [joshwlewis/unitwise#58]
Not much to say other than the trace. Ruby 2.5.1. Unitwise 2.2.0.

```
⟪wise_units⟫  004:0> Unitwise(1, "[p'diop]").convert_to("rad")
NoMethodError: undefined method `from_100tan' for Unitwise::Functional:Class
Did you mean?  from_tan100
        from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/functional.rb:114:in `scalar'
        from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/atom.rb:106:in `scalar'
        from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/term.rb:63:in `scalar'
        from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/unit.rb:91:in `block in scalar'
        from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/unit.rb:90:in `each'
        from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/unit.rb:90:in `reduce'
        from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/unit.rb:90:in `scalar'
        from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/scale.rb:53:in `scalar'
        from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/measurement.rb:165:in `converted_value'
        from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/measurement.rb:29:in `convert_to'
        from (irb):4
```

**Comment by turboladen** [comment]
Looks like the same for other special units as well:

```
008:0> Unitwise(1, "[pH]").convert_to("mol/l")
NoMethodError: undefined method `from_pH' for Unitwise::Functional:Class
Did you mean?  from_hpX
               from_hpC
               from_lg
               from_ln
               from_ld
        from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/functional.rb:114:in `scalar'
        from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/atom.rb:106:in `scalar'
        from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/term.rb:63:in `scalar'
        from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/unit.rb:91:in `block in scalar'
        from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/unit.rb:90:in `each'
        from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/unit.rb:90:in `reduce'
        from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/unit.rb:90:in `scalar'
        from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/scale.rb:53:in `scalar'
        from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/measurement.rb:165:in `converted_value'
        from /Users/sloveless/.gem/ruby/2.5.1/gems/unitwise-2.2.0/lib/unitwise/measurement.rb:29:in `convert_to'
```

**Comment by stevegeek** [comment]
Fixed in #84
